import { PointData, MatchResultMeta } from "@/types";

type TestData = {
  users: {
    id: string;
    name: string;
    password: string;
  }[];
  point: (PointData & { id: string; matchId: string })[];
  matchMeta: MatchResultMeta[];
};

export const testData: TestData = {
  users: [
    {
      id: "1",
      name: "田中",
      password: "password",
    },
  ],
  point: [
    {
      id: "1",
      matchId: "1",
      server: "A1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A2",
      playType: "backhandhighvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747223324167,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 1,
    },
    {
      id: "2",
      matchId: "1",
      server: "A1",
      firstServeIn: true,
      rallyLength: "long",
      player: "A1",
      playType: "backhandhighvolley",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747223331887,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 1,
      gameNumber: 1,
    },
    {
      id: "3",
      matchId: "1",
      server: "A2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B1",
      playType: "backhandstroke",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223338982,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 2,
      gameNumber: 1,
    },
    {
      id: "4",
      matchId: "1",
      server: "A2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B2",
      playType: "smash",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223345251,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 3,
      gameNumber: 1,
    },
    {
      id: "5",
      matchId: "1",
      server: "A1",
      firstServeIn: true,
      rallyLength: "long",
      player: "A2",
      playType: "forehandvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747223353959,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 3,
      gameNumber: 1,
    },
    {
      id: "6",
      matchId: "1",
      server: "A1",
      firstServeIn: true,
      rallyLength: "short",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747223359494,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 2,
    },
    {
      id: "7",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A2",
      playType: "backhandvolley",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223371022,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 2,
    },
    {
      id: "8",
      matchId: "1",
      server: "B1",
      firstServeIn: true,
      rallyLength: "short",
      player: "A2",
      playType: "backhandreception",
      ballCourse: "cross",
      errorCause: "net",
      timestamp: 1747223389092,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 1,
      teamBScore: 1,
      gameNumber: 2,
    },
    {
      id: "9",
      matchId: "1",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747223398617,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 1,
      teamBScore: 2,
      gameNumber: 2,
    },
    {
      id: "10",
      matchId: "1",
      server: "B2",
      firstServeIn: true,
      rallyLength: "long",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747223406312,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 2,
      teamBScore: 2,
      gameNumber: 2,
    },
    {
      id: "11",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "short",
      player: "B2",
      playType: "forehandhighvolley",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223415336,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 2,
      teamBScore: 3,
      gameNumber: 2,
    },
    {
      id: "12",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "short",
      player: "B2",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747223423580,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 3,
      teamBScore: 3,
      gameNumber: 2,
    },
    {
      id: "13",
      matchId: "1",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747223434815,
      teamAGames: 0,
      teamBGames: 1,
      teamAScore: 3,
      teamBScore: 4,
      gameNumber: 2,
    },
    {
      id: "14",
      matchId: "1",
      server: "B2",
      firstServeIn: false,
      rallyLength: "long",
      player: "A1",
      playType: "backhandstroke",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747223444063,
      teamAGames: 0,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 3,
    },
    {
      id: "15",
      matchId: "1",
      server: "A1",
      firstServeIn: true,
      rallyLength: "long",
      player: "A2",
      playType: "forehandhighvolley",
      ballCourse: "cross",
      timestamp: 1747223457782,
      teamAGames: 0,
      teamBGames: 2,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 3,
    },
    {
      id: "16",
      matchId: "1",
      server: "A1",
      firstServeIn: false,
      rallyLength: "long",
      player: "B1",
      playType: "backhandstroke",
      ballCourse: "cross",
      errorCause: "net",
      timestamp: 1747223468792,
      teamAGames: 0,
      teamBGames: 2,
      teamAScore: 2,
      teamBScore: 0,
      gameNumber: 3,
    },
    {
      id: "17",
      matchId: "1",
      server: "A2",
      firstServeIn: false,
      rallyLength: "long",
      player: "B1",
      playType: "backhandstroke",
      ballCourse: "cross",
      errorCause: "net",
      timestamp: 1747223484108,
      teamAGames: 0,
      teamBGames: 2,
      teamAScore: 3,
      teamBScore: 0,
      gameNumber: 3,
    },
    {
      id: "18",
      matchId: "1",
      server: "A2",
      firstServeIn: false,
      rallyLength: "long",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747223492209,
      teamAGames: 0,
      teamBGames: 2,
      teamAScore: 3,
      teamBScore: 1,
      gameNumber: 3,
    },
    {
      id: "19",
      matchId: "1",
      server: "A1",
      firstServeIn: false,
      rallyLength: "long",
      player: "B2",
      playType: "backhandvolley",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747223501157,
      teamAGames: 1,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 4,
    },
    {
      id: "20",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747223511785,
      teamAGames: 1,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 1,
      gameNumber: 4,
    },
    {
      id: "21",
      matchId: "1",
      server: "B1",
      firstServeIn: true,
      rallyLength: "short",
      player: "A2",
      playType: "backhandhighvolley",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747223517320,
      teamAGames: 1,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 2,
      gameNumber: 4,
    },
    {
      id: "22",
      matchId: "1",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747223522144,
      teamAGames: 1,
      teamBGames: 2,
      teamAScore: 1,
      teamBScore: 2,
      gameNumber: 4,
    },
    {
      id: "23",
      matchId: "1",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B2",
      playType: "backhandlowvolley",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747223530701,
      teamAGames: 1,
      teamBGames: 2,
      teamAScore: 2,
      teamBScore: 2,
      gameNumber: 4,
    },
    {
      id: "24",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223537880,
      teamAGames: 1,
      teamBGames: 2,
      teamAScore: 3,
      teamBScore: 2,
      gameNumber: 4,
    },
    {
      id: "25",
      matchId: "1",
      server: "B1",
      firstServeIn: true,
      rallyLength: "long",
      player: "B2",
      playType: "backhandhighvolley",
      ballCourse: "cross",
      errorCause: "back_out",
      timestamp: 1747223546131,
      teamAGames: 2,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 5,
    },
    {
      id: "26",
      matchId: "1",
      server: "A1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A2",
      playType: "forehandlowvolley",
      ballCourse: "cross",
      errorCause: "side_out",
      timestamp: 1747223556182,
      teamAGames: 2,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 1,
      gameNumber: 5,
    },
    {
      id: "27",
      matchId: "1",
      server: "A1",
      firstServeIn: true,
      rallyLength: "long",
      player: "A2",
      playType: "forehandvolley",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223562211,
      teamAGames: 2,
      teamBGames: 2,
      teamAScore: 1,
      teamBScore: 1,
      gameNumber: 5,
    },
    {
      id: "28",
      matchId: "1",
      server: "A2",
      firstServeIn: false,
      rallyLength: "short",
      player: "A1",
      playType: "backhandstroke",
      ballCourse: "cross",
      errorCause: "net",
      timestamp: 1747223568580,
      teamAGames: 2,
      teamBGames: 2,
      teamAScore: 1,
      teamBScore: 2,
      gameNumber: 5,
    },
    {
      id: "29",
      matchId: "1",
      server: "A2",
      firstServeIn: true,
      rallyLength: "long",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223574205,
      teamAGames: 2,
      teamBGames: 2,
      teamAScore: 2,
      teamBScore: 2,
      gameNumber: 5,
    },
    {
      id: "30",
      matchId: "1",
      server: "A1",
      firstServeIn: false,
      rallyLength: "short",
      player: "B2",
      playType: "forehandlowvolley",
      ballCourse: "cross",
      errorCause: "back_out",
      timestamp: 1747223586027,
      teamAGames: 2,
      teamBGames: 2,
      teamAScore: 3,
      teamBScore: 2,
      gameNumber: 5,
    },
    {
      id: "31",
      matchId: "1",
      server: "A1",
      firstServeIn: true,
      rallyLength: "short",
      player: "B1",
      playType: "backhandstroke",
      ballCourse: "cross",
      errorCause: "side_out",
      timestamp: 1747223593024,
      teamAGames: 3,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 6,
    },
    {
      id: "32",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "short",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747223600195,
      teamAGames: 3,
      teamBGames: 2,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 6,
    },
    {
      id: "33",
      matchId: "1",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A2",
      playType: "backhandvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747223608219,
      teamAGames: 3,
      teamBGames: 2,
      teamAScore: 2,
      teamBScore: 0,
      gameNumber: 6,
    },
    {
      id: "34",
      matchId: "1",
      server: "B2",
      firstServeIn: false,
      rallyLength: "long",
      player: "B2",
      playType: "backhandhighvolley",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747223617012,
      teamAGames: 3,
      teamBGames: 2,
      teamAScore: 3,
      teamBScore: 0,
      gameNumber: 6,
    },
    {
      id: "35",
      matchId: "1",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "A1",
      playType: "backhandstroke",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747223625778,
      teamAGames: 3,
      teamBGames: 2,
      teamAScore: 3,
      teamBScore: 1,
      gameNumber: 6,
    },
    {
      id: "36",
      matchId: "1",
      server: "B1",
      firstServeIn: true,
      rallyLength: "short",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747223632980,
      teamAGames: 4,
      teamBGames: 2,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 7,
    },

    {
      id: "37",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A2",
      playType: "forehandhighvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747225212494,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 1,
    },
    {
      id: "38",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747225226738,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 1,
      gameNumber: 1,
    },
    {
      id: "39",
      matchId: "2",
      server: "B2",
      firstServeIn: false,
      rallyLength: "short",
      player: "B2",
      playType: "serve",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747225241799,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 1,
      gameNumber: 1,
    },
    {
      id: "40",
      matchId: "2",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "A1",
      playType: "backhandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747225252833,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 2,
      gameNumber: 1,
    },
    {
      id: "41",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "B1",
      playType: "backhandstroke",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747225259319,
      teamAGames: 0,
      teamBGames: 0,
      teamAScore: 3,
      teamBScore: 2,
      gameNumber: 1,
    },
    {
      id: "42",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "B2",
      playType: "backhandhighvolley",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747225266963,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 2,
    },
    {
      id: "43",
      matchId: "2",
      server: "A1",
      firstServeIn: false,
      rallyLength: "short",
      player: "A2",
      playType: "forehandvolley",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747225273817,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 2,
    },
    {
      id: "44",
      matchId: "2",
      server: "A1",
      firstServeIn: true,
      rallyLength: "short",
      player: "A1",
      playType: "backhandstroke",
      ballCourse: "cross",
      errorCause: "net",
      timestamp: 1747225280359,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 1,
      gameNumber: 2,
    },
    {
      id: "45",
      matchId: "2",
      server: "A2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "cross",
      errorCause: "back_out",
      timestamp: 1747225286824,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 1,
      gameNumber: 2,
    },
    {
      id: "46",
      matchId: "2",
      server: "A2",
      firstServeIn: false,
      rallyLength: "long",
      player: "B2",
      playType: "forehandhighvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747225296366,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 2,
      gameNumber: 2,
    },
    {
      id: "47",
      matchId: "2",
      server: "A1",
      firstServeIn: true,
      rallyLength: "short",
      player: "A2",
      playType: "backhandlowvolley",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747225306182,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 3,
      gameNumber: 2,
    },
    {
      id: "48",
      matchId: "2",
      server: "A1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747225314329,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 3,
      teamBScore: 3,
      gameNumber: 2,
    },
    {
      id: "49",
      matchId: "2",
      server: "A2",
      firstServeIn: true,
      rallyLength: "long",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747225322541,
      teamAGames: 1,
      teamBGames: 0,
      teamAScore: 4,
      teamBScore: 3,
      gameNumber: 2,
    },
    {
      id: "50",
      matchId: "2",
      server: "A2",
      firstServeIn: false,
      rallyLength: "long",
      player: "B2",
      playType: "forehandhighvolley",
      ballCourse: "cross",
      errorCause: "net",
      timestamp: 1747225333238,
      teamAGames: 2,
      teamBGames: 0,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 3,
    },
    {
      id: "51",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A2",
      playType: "backhandvolley",
      ballCourse: "cross",
      errorCause: undefined,
      timestamp: 1747225340707,
      teamAGames: 2,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 0,
      gameNumber: 3,
    },
    {
      id: "52",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "long",
      player: "A1",
      playType: "backhandstroke",
      ballCourse: "straight",
      errorCause: "back_out",
      timestamp: 1747225348659,
      teamAGames: 2,
      teamBGames: 0,
      teamAScore: 1,
      teamBScore: 1,
      gameNumber: 3,
    },
    {
      id: "53",
      matchId: "2",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B1",
      playType: "forehandstroke",
      ballCourse: "straight",
      errorCause: "side_out",
      timestamp: 1747225354202,
      teamAGames: 2,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 1,
      gameNumber: 3,
    },
    {
      id: "54",
      matchId: "2",
      server: "B2",
      firstServeIn: true,
      rallyLength: "short",
      player: "B2",
      playType: "forehandhighvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747225357831,
      teamAGames: 2,
      teamBGames: 0,
      teamAScore: 2,
      teamBScore: 2,
      gameNumber: 3,
    },
    {
      id: "55",
      matchId: "2",
      server: "B1",
      firstServeIn: true,
      rallyLength: "short",
      player: "A2",
      playType: "backhandvolley",
      ballCourse: "straight",
      errorCause: undefined,
      timestamp: 1747225365174,
      teamAGames: 2,
      teamBGames: 0,
      teamAScore: 3,
      teamBScore: 2,
      gameNumber: 3,
    },
    {
      id: "56",
      matchId: "2",
      server: "B1",
      firstServeIn: false,
      rallyLength: "short",
      player: "B1",
      playType: "backhandstroke",
      ballCourse: "straight",
      errorCause: "net",
      timestamp: 1747225374610,
      teamAGames: 3,
      teamBGames: 0,
      teamAScore: 0,
      teamBScore: 0,
      gameNumber: 4,
    },
  ],
  matchMeta: [
    {
      id: "1",
      ownerId: "1",
      matchLength: 7,
      teamAName: "北高校",
      teamBName: "南高校",
      playerA1Name: "田中",
      playerA2Name: "鈴木",
      playerB1Name: "佐藤",
      playerB2Name: "高橋",
      initialServer: "A1",
      teamAGames: 4,
      teamBGames: 2,
      savedAt: new Date("2024-03-15"),
    },
    {
      id: "2",
      ownerId: "1",
      matchLength: 5,
      teamAName: "東京大学",
      teamBName: "京都大学",
      playerA1Name: "佐々木",
      playerA2Name: "勝俣",
      playerB1Name: "多井",
      playerB2Name: "日向",
      initialServer: "B1",
      teamAGames: 3,
      teamBGames: 0,
      savedAt: new Date("2024-03-16"),
    },
  ],
};
